// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLibraryBackendWebAPI.Data;

#nullable disable

namespace MusicLibraryBackendWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MusicLibraryBackendWebAPI.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "808s & Heartbreak",
                            Artist = "Kanye West",
                            Genre = "Hip-Hop",
                            ReleaseDate = 2008,
                            Title = "Amazing"
                        },
                        new
                        {
                            Id = 2,
                            Album = "808s & Heartbreak",
                            Artist = "Kanye West",
                            Genre = "Hip-Hop",
                            ReleaseDate = 2008,
                            Title = "Heartless"
                        },
                        new
                        {
                            Id = 3,
                            Album = "DAMN",
                            Artist = "Kendrick Lamar",
                            Genre = "Hip-Hop",
                            ReleaseDate = 2017,
                            Title = "DNA"
                        },
                        new
                        {
                            Id = 4,
                            Album = "DAMN",
                            Artist = "Kendrick Lamar",
                            Genre = "Hip-Hop",
                            ReleaseDate = 2017,
                            Title = "PRIDE"
                        },
                        new
                        {
                            Id = 5,
                            Album = "The Slow Rush",
                            Artist = "Tame Impala",
                            Genre = "Psychedelic Rock",
                            ReleaseDate = 2020,
                            Title = "Borderline"
                        },
                        new
                        {
                            Id = 6,
                            Album = "Currents",
                            Artist = "Tame Impala",
                            Genre = "Psychedelic Rock",
                            ReleaseDate = 2015,
                            Title = "Let It Happen"
                        },
                        new
                        {
                            Id = 7,
                            Album = "Frank",
                            Artist = "Amy Winehouse",
                            Genre = "Jazz",
                            ReleaseDate = 2003,
                            Title = "Stronger Than Me"
                        },
                        new
                        {
                            Id = 8,
                            Album = "Back to Black",
                            Artist = "Amy Winehouse",
                            Genre = "Jazz",
                            ReleaseDate = 2006,
                            Title = "Love Is A Losing Game"
                        },
                        new
                        {
                            Id = 9,
                            Album = "channel ORANGE",
                            Artist = "Frank Ocean",
                            Genre = "Neo Soul",
                            ReleaseDate = 2012,
                            Title = "Pink Matter"
                        },
                        new
                        {
                            Id = 10,
                            Album = "Blonde",
                            Artist = "Frank Ocean",
                            Genre = "Neo Soul",
                            ReleaseDate = 2016,
                            Title = "Nights"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
